name: CI
on: [push]
jobs:
  build:
    name: Test-Bob
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install --production=false
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint
